config/routes.rb
Rails.application.routes.draw do

  root to: "dashboard#index"

  resources :working_days
  resources :dashboard, only:[:index]


  get 'users/schedule/:id' => "schedules#render_schedule"

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
  }

  resources :users do
    resource :schedule, only: [:create, :show]
  end


end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	def index
		@users = User.all
	end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="container">

	<% if user_signed_in? %>
	<div class="jumbotron">
		<h1 class="display-4">Welcome <%= current_user.email %></h1>
		<%= link_to('Edit registration', edit_user_registration_path, class:"btn btn-primary") %>
		<%= link_to('Logout', destroy_user_session_path, class:"btn btn-danger", :method => :delete) %>        

		<% else %>

		<%= link_to('Register', new_user_registration_path)  %>
		<%= link_to('Login', new_user_session_path)  %>  

		<% end %>

	</div>


	<h1>Dashboard</h1>

	<% if current_user.type && current_user.type=='Admin' %>
	<p>Visible only for admins! </p>
	
	<% end %>

	<% if can? :manage, :all %> 
	<p>Admins can manage all! </p>
	<h1>Users</h1>

	<table>
	  <thead>
	    <tr>
	      <th>Name</th>
	      <th colspan="3"></th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @users.each do |user| %>
	      <tr>
	        <td><%= user.name %></td>
	        <td><%= link_to 'Show', users_path %></td>
	        <td><%= link_to 'Schedule', user_schedule_path(user) %></td>
	        <td><%= link_to 'Edit', edit_user_registration_path+'/'+user.id.to_s %></td>
	        <td><%= link_to 'Destroy', 'user', method: :delete, data: { confirm: 'Are you sure?' } %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>

	<br>

	<% end %>

	<% if can? :manage, User %> <p>This account can manage this user! id: <%= current_user.id %> </p> <% end %>




	<% unless current_user.type == 'Admin' %>
	<td><%= link_to 'Show my profile', "user/"+current_user.id.to_s %></td>
	<% end %>

</div>