config/routes.rb
Rails.application.routes.draw do

  root to: "dashboard#index"

  resources :working_days
  resources :dashboard, only:[:index]


  get 'users/schedule/:id' => "schedules#render_schedule"

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
  }

  resources :users do
    resource :schedule, only: [:create, :show]
  end


end

app/models/working_day.rb
class WorkingDay < ApplicationRecord
	belongs_to :user

	scope :by_user, ->(user_id) { where(user_id: user_id) }
end

app/controllers/working_days_controller.rb
class WorkingDaysController < ApplicationController
  before_action :set_working_day, only: [:show, :edit, :update, :destroy]

  # GET /working_days
  # GET /working_days.json
  def index
    @working_days = WorkingDay.all
  end

  # GET /working_days/1
  # GET /working_days/1.json
  def show
    
  end

  # GET /working_days/new
  def new
    @working_day = WorkingDay.new
  end

  # GET /working_days/1/edit
  def edit
  end

  # POST /working_days
  # POST /working_days.json
  def create
    @working_day = WorkingDay.new(working_day_params)

    respond_to do |format|
      if @working_day.save
        format.html { redirect_to @working_day, notice: 'Working day was successfully created.' }
        format.json { render :show, status: :created, location: @working_day }
      else
        format.html { render :new }
        format.json { render json: @working_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /working_days/1
  # PATCH/PUT /working_days/1.json
  def update
    respond_to do |format|
      if @working_day.update(working_day_params)
        format.html { redirect_to @working_day, notice: 'Working day was successfully updated.' }
        format.json { render :show, status: :ok, location: @working_day }
      else
        format.html { render :edit }
        format.json { render json: @working_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /working_days/1
  # DELETE /working_days/1.json
  def destroy
    @working_day.destroy
    respond_to do |format|
      format.html { redirect_to working_days_url, notice: 'Working day was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_working_day
      @working_day = WorkingDay.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def working_day_params
      params.require(:working_day).permit(:user_id, :arrival, :break_start, :break_end, :departure)
    end
end

app/helpers/working_days_helper.rb
module WorkingDaysHelper
end

app/views/working_days/_form.html.erb
<%= form_with(model: working_day, local: true) do |form| %>
  <% if working_day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(working_day.errors.count, "error") %> prohibited this working_day from being saved:</h2>

      <ul>
      <% working_day.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :arrival %>
    <%= form.datetime_select :arrival %>
  </div>

  <div class="field">
    <%= form.label :break_start %>
    <%= form.datetime_select :break_start %>
  </div>

  <div class="field">
    <%= form.label :break_end %>
    <%= form.datetime_select :break_end %>
  </div>

  <div class="field">
    <%= form.label :departure %>
    <%= form.datetime_select :departure %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/working_days/edit.html.erb
<h1>Editing Working Day</h1>

<%= render 'form', working_day: @working_day %>

<%= link_to 'Show', @working_day %> |
<%= link_to 'Back', working_days_path %>

app/views/working_days/index.html.erb
<% if can? :manage, :all %>
<p id="notice"><%= notice %></p>

<h1>Working Days</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Arrival</th>
      <th>Break start</th>
      <th>Break end</th>
      <th>Departure</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @working_days.each do |working_day| %>
      <tr>
        <td><%= working_day.user_id %></td>
        <td><%= working_day.arrival %></td>
        <td><%= working_day.break_start %></td>
        <td><%= working_day.break_end %></td>
        <td><%= working_day.departure %></td>
        <td><%= link_to 'Show', working_day %></td>
        <td><%= link_to 'Edit', edit_working_day_path(working_day) %></td>
        <td><%= link_to 'Destroy', working_day, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Working Day', new_working_day_path %>

<% else %>
<% controller.redirect_to dashboard_path %>
<% end %>

app/views/working_days/new.html.erb
<h1>New Working Day</h1>

<%= render 'form', working_day: @working_day %>

<%= link_to 'Back', working_days_path %>

app/views/working_days/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @working_day.user_id %>
</p>

<p>
  <strong>Arrival:</strong>
  <%= @working_day.arrival %>
</p>

<p>
  <strong>Break start:</strong>
  <%= @working_day.break_start %>
</p>

<p>
  <strong>Break end:</strong>
  <%= @working_day.break_end %>
</p>

<p>
  <strong>Departure:</strong>
  <%= @working_day.departure %>
</p>

<%= link_to 'Edit', edit_working_day_path(@working_day) %> |
<%= link_to 'Back', working_days_path %>